name: notepad
description: A simple notes app with Hive

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  share_plus: ^7.0.2
  intl: ^0.20.2
  awesome_notifications: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
